providers = ["php"]

[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "git",
  "unzip",
  "curl",
  "libzip"
]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"

