[phases.setup]
nixPkgs = [
    "php80",
    "php80Extensions.curl",
    "php80Extensions.mbstring",
    "php80Extensions.openssl",
    "php80Extensions.pdo_mysql",
    "php80Extensions.tokenizer",
    "php80Extensions.xml",
    "php80Extensions.fileinfo",
    "php80Extensions.sodium",
    "composer",
    "nodejs-18_x",
    "yarn"
]

[phases.build]
commands = [
    "composer install --no-dev",
    "yarn install",
    "php artisan key:generate",
    "php artisan storage:link"
]
